<?php

namespace PostsRest\Controller;

use Zend\Mvc\Controller\AbstractRestfulController;
use Zend\View\Model\JsonModel;
use MyBlog\Entity\Posts;
use Doctrine\ORM\EntityManager;
use Application\Models\AclAccess;
use Zend\Mvc\MvcEvent;

class PostsRestController extends AbstractRestfulController
{

    public function onDispatch(MvcEvent $e)
    {
        $routeMatch = $e->getRouteMatch();
        $action = $routeMatch->getParam('action', false);
        if(!$action && $this->getRequest()->isPost()){
            $e->setResult($this->connect());
            return $this->connect();
        } else {
            return parent::onDispatch($e); // TODO: Change the autogenerated stub
        }
    }

    public function connect(){
        return array('access-token' => 'dsaoijdoajisdjasdoasjid');
    }

    /*
    public function getList()
    {

        $request = $this->getRequest();
        //if($request->isPost)
        if($this->authorization('sergei', '123456')){

        }

        return array('server' => 'Incorrect access data or you have no permissions to access this operation!');
    }
    */

    public function get($id)
    {
        return array('data' => 'get');
    }

    public function create($data)
    {
        return array('data' => 'post');
    }

    public function update($id, $data)
    {
        return array('data' => 'put');
    }

    public function delete($id)
    {
        return array('data' => 'delete');
    }

    public function authorization($username, $password)
    {
        $em = $this->getServiceLocator()->get('Doctrine\ORM\EntityManager');
        $user = $em->getRepository('MyBlog\Entity\Users')->findBy(array('userName' => $username, 'userPassword' => hash('sha256', $password)));
        if(!$user){
            return false;
        }
        return true;
    }

}