<?php

?>
<?php echo $this->messages; ?>

<?php

    $form = $this->form;
    $form->prepare();

    echo $this->form()->openTag($form);
    echo $this->formRow($form->get('user_name'));
    echo $this->formRow($form->get('user_password'));
    echo $this->formSubmit($form->get('submit'));
    echo $this->form()->closeTag();

?>

<?php
    try {
        if($user = $this->identity()) {
            echo 'Авторизован как: ' . $this->escapeHtml($user->getUserName()).'<br/>';
            ?>
            <br>
            <a href="<?php echo $this->url('auth-doctrine/default', array('controller' => 'index', 'action' => 'logout')); ?>">
                Выход
            </a>
            <?php
        }
        else{
            echo 'Вход не выполнен!';
        }
    }
    catch(Exception $e){
        //echo $e->getMessage();
    }
?>
<br/>
<a href="<?php echo $this->url('auth-doctrine/default', array('controller' => 'index', 'action' => 'register')); ?>">
    Регистрация
</a>
