<?php
    echo $this->headLink()->appendStylesheet('/css/login.css');
    $this->headTitle('Login');
    //if(empty($this->identity())){
    //    echo 'empty<br/>';
    //}
    //echo $this->identity()->getUserName();
?>
<div class="container">
    <div class="row">

        <h1><?= $this->escapeHtml('Login Page') ?></h1>

        <?php $this->form->prepare(); ?>

        <div class="loginBlock">
            <?= $this->form()->openTag($this->form) ?>
            <?= $this->formRow($form->get('user_name')) ?><br/>
            <?= $this->formRow($form->get('user_password')) ?><br/>
            <div class="errorMessage"><?php echo $this->messages; ?></div>
            <div class="checkbox">
                <label>
                    <?= $this->formRow($form->get('rememberme')) ?>
                    Remember me
                </label>
            </div>
            <?= $this->formSubmit($form->get('submit')) ?>
            <?= $this->form()->closeTag() ?>

        </div>

    </div>
</div>
