<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle(''. $this->translate('Simple Blog'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Simple Blog"/>&nbsp;<?php echo $this->translate('Simple Blog') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <?php if(empty($this->identity())): ?>
                            <li><a href="<?php echo $this->url('auth-doctrine/default', array('controller' => 'registration', 'action' => 'index')) ?>"><?php echo $this->translate('Registration') ?></a></li>
                            <li><a href="<?php echo $this->url('auth-doctrine/default', array('controller' => 'index', 'action' => 'login')) ?>"><?php echo $this->translate('Login') ?></a></li>
                        <?php else: ?>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><?php echo $this->translate('Hello').', '.$this->identity()->getUserFullName().' '; ?><span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <?php if($this->identity()->getUserRole() == 'admin'): ?>
                                        <li><a href="<?php echo $this->url('admin/default', array('controller' => 'index', 'action' => 'index')) ?>">AdminPanel</a></li>
                                    <?php endif; ?>
                                    <?php if($this->identity()->getUserRole() == 'admin' || $this->identity()->getUserRole() == 'manager'): ?>
                                        <li><a href="<?php echo $this->url('posts/default', array('controller' => 'index', 'action' => 'create-post')) ?>">Create post</a></li>
                                    <?php endif; ?>
                                    <li><a href="<?php echo $this->url('auth-doctrine/default', array('controller' => 'index', 'action' => 'logout')) ?>">Logout</a></li>
                                    <!--<li role="separator" class="divider"></li>-->
                                </ul>
                            </li>
                        <?php endif; ?>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2016 - <?php echo date('Y') ?> by Simple Blog Team. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
