<?php echo $this->headLink()->appendStylesheet('/css/login.css'); ?>
<?php $this->headTitle('Registration') ?>
<div class="container">
    <div class="row">

        <?php $this->form->prepare(); ?>
        <h1><?= $this->escapeHtml('Registration Page') ?></h1>
        <div class="loginBlock">

            <?php
                $flash = $this->flashMessenger();
                $flash->setMessageOpenFormat('<div%s>
                     <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                         &times;
                     </button>
                     <ul><li>')
                    ->setMessageSeparatorString('</li><li>')
                    ->setMessageCloseString('</li></ul></div>');

                echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
                echo $flash->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
                echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
                echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
            ?>

            <?= $this->form()->openTag($this->form) ?>
            <?= $this->formRow($form->get('user_name')) ?><br/>
            <?= $this->formRow($form->get('user_password')) ?><br/>
            <?= $this->formRow($form->get('user_email')) ?><br/>
            <?= $this->formRow($form->get('user_fullname')) ?><br/>
        </div>
        <div class="verifyBlock">
            <?= $this->formRow($form->get('captcha')) ?><br/>
        </div>
        <div class="loginBlock">
            <div class="errorMessage"><?php //echo (!empty($this->message))?($this->message):(''); ?><br/><br/></div>
            <?= $this->formSubmit($form->get('submit')) ?>
            <?= $this->form()->closeTag() ?>
        </div>


    </div>
</div>