<?php echo $this->headLink()->appendStylesheet('/css/login.css'); ?>
<?php echo $this->headScript()->prependFile('/js/user-edit.js'); ?>
<!--<script src="../../../../../public/js/user-edit.js"></script>-->
<?php $this->headTitle('AdminCenter') ?>
<div class="container">
    <div class="row">

        <h3><?= $this->escapeHtml('Edit user:') ?></h3>

        <?php $this->form->prepare(); ?>
        <div class="loginBlock">

            <?php
            $flash = $this->flashMessenger();
            $flash->setMessageOpenFormat('<div%s>
                     <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                         &times;
                     </button>
                     <ul><li>')
                ->setMessageSeparatorString('</li><li>')
                ->setMessageCloseString('</li></ul></div>');

            echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
            echo $flash->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
            echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
            echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
            ?>

            <?= $this->form()->openTag($this->form) ?>
            <?= $this->formRow($form->get('user_name')) ?><br/>
            <?= $this->formRow($form->get('user_email')) ?><br/>
            <?= $this->formRow($form->get('user_fullname')) ?>
            <?= $this->formRow($form->get('role')) ?>
            <div class="errorMessage"><?php //echo (!empty($this->message))?($this->message):(''); ?><br/></div>
            <select class="form-control" id="selectRole">
                <option><?php echo $this->user->getUserRole(); ?></option>
                <?php foreach($this->acl->getRolesArray() as $role): ?>
                    <?php if($role != $this->user->getUserRole()): ?>
                        <option><?php echo $role; ?></option>
                    <?php endif; ?>
                <?php endforeach; ?>
            </select><br/>
            <?= $this->formSubmit($form->get('submit')) ?>
            <?= $this->form()->closeTag() ?>
        </div>

    </div>
</div>


