<?php if(!$this->identity()): ?>
    <div class="panel panel-default">
        <div id="vk_auth"></div>
        <script type="text/javascript">
            VK.Widgets.Auth("vk_auth", {width: "360px", authUrl: '/vk/index/login'});
        </script>
    </div>
<?php endif; ?>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Users Online (<?php echo count($this->usersOnline); ?>)</h3>
    </div>
    <div class="panel-body">
        <?php foreach($this->usersOnline as $id => $userOnline): ?>
            <span class="glyphicon glyphicon-user"></span>&nbsp;<?php echo $userOnline['userName']; ?><div class="fullTime">&nbsp;(<?php echo $userOnline['fullTime']; ?>h)</div>&nbsp;
        <?php endforeach; ?>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Popular posts</h3>
    </div>
    <div class="panel-body">
        <?php foreach($this->popularPosts as $id => $post): ?>
            Title: <a href="<?php echo $this->url('application/default', array('controller' => 'index', 'action' => 'show', 'id' => $post['id'])); ?>"><?php echo $post['title']; ?></a><br/>
            Description: <br/><?php echo $post['text']; ?><br/>
            <div class="postBottom_left">
                <?php echo $post['created']; ?>
            </div>
            <div class="postHeader_right">
                <div class="addLikeTop"><span class="glyphicon glyphicon-heart"></span>&nbsp;<?php echo $post['likes']; ?></div>
            </div>
            <hr/>
        <?php endforeach; ?>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title"><?php echo $this->translate('5 latest news') ?></h3>
    </div>
    <div class="panel-body">
        <?php foreach($this->top as $top): ?>
            <a href="<?php echo $this->url('application/default', array('controller' => 'index', 'action' => 'show', 'id' => $top->getId())); ?>"><?php echo $top->getTitle(); ?></a> /
        <?php endforeach; ?>
    </div>
</div>