<div class="row">
    <br/>

    <div class="col-md-8">

        <?php
        $flash = $this->flashMessenger();
        $flash->setMessageOpenFormat('<div%s>
                     <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                         &times;
                     </button>
                     <ul><li>')
            ->setMessageSeparatorString('</li><li>')
            ->setMessageCloseString('</li></ul></div>');

        echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
        echo $flash->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
        echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
        echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
        ?>

        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Follow Development') ?></h3>
            </div>
            <div class="panel-body">
                <br/><br/><br/>
            </div>
        </div>

    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('5 latest news') ?></h3>
            </div>
            <div class="panel-body">

            </div>
        </div>
    </div>
</div>
