<?php echo $this->headLink()->appendStylesheet('/css/login.css'); ?>
<?php //echo $this->headLink()->appendStylesheet('/js/tinyslider2/style.css'); ?>
<?php //echo $this->headScript()->prependFile('/js/tinyslider2/script.js'); ?>
<?php echo $this->headLink()->appendStylesheet('/js/picture-slider/style.css'); ?>
<?php echo $this->headScript()->prependFile('/js/picture-slider/script.js'); ?>
<div class="row">
    <br/>
    <div class="col-md-8">

        <?php
        $flash = $this->flashMessenger();
        $flash->setMessageOpenFormat('<div%s>
                     <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                         &times;
                     </button>
                     <ul><li>')
            ->setMessageSeparatorString('</li><li>')
            ->setMessageCloseString('</li></ul></div>');

        echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
        echo $flash->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
        echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
        echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
        ?>

        <?php foreach($this->posts as $id => $post): ?>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div <?php $acl = $this->acl; if($this->identity()): if($this->acl->isAllowed($this->identity()->getUserRole(), $acl::NEWS)): ?> class="postHeader_left" <?php endif; endif; ?> >
                        <h4 class="panel-title"><?php echo $this->translate($post[key($post)]->getTitle()); ?></h4>
                    </div>
                    <?php if($this->identity()): if($this->acl->isAllowed($this->identity()->getUserRole(), $acl::NEWS)): ?>
                        <div class="postHeader_right">
                            <a href="<?php echo $this->url('posts/default', array('controller' => 'index', 'action' => 'post-edit', 'id' => $post[key($post)]->getId())); ?>"><span class="glyphicon glyphicon-edit"></span></a>
                            <a href="<?php echo $this->url('posts/default', array('controller' => 'index', 'action' => 'post-delete', 'id' => $post[key($post)]->getId())); ?>"><span class="glyphicon glyphicon-trash"></span></a>
                        </div>
                    <?php endif; endif; ?>
                </div>
                <div class="panel-body">

                <!--<div id="wrapperPicture">
                    <div id="containerPicture">
                        <div class="sliderbutton" id="slideleft" onclick="slideshow.move(-1)"></div>
                        <div id="slider">
                            <ul>
                                <li><img src="/js/tinyslider2/photos/1.jpg" width="558" height="235" alt="Image One" /></li>
                                <li><img src="/js/tinyslider2/photos/2.jpg" width="558" height="235" alt="Image Two" /></li>
                                <li><img src="/js/tinyslider2/photos/3.jpg" width="558" height="235" alt="Image Three" /></li>
                                <li><img src="/js/tinyslider2/photos/4.jpg" width="558" height="235" alt="Image Four" /></li>
                            </ul>
                        </div>
                        <div class="sliderbutton" id="slideright" onclick="slideshow.move(1)"></div>
                        <ul id="pagination" class="pagination">
                            <li onclick="slideshow.pos(0)"></li>
                            <li onclick="slideshow.pos(1)"></li>
                            <li onclick="slideshow.pos(2)"></li>
                            <li onclick="slideshow.pos(3)"></li>
                        </ul><br/>
                    </div>
                </div>-->
                    <?php if($this->identity()): ?>
                        <div class="slider">
                            <ul>
                                <li><img src="/img/tests/1.jpg" alt="" width="800px"></li>
                                <li><img src="/img/tests/2.jpg" alt="" width="800px"></li>
                            </ul>
                        </div>
                    <?php endif; ?>

                    <?php echo $post[key($post)]->getText(); ?>
                    <hr/>
                    <div class="postBottom_left">
                        <?php echo key($post).': '.$post[key($post)]->getCreated(); ?>
                    </div>
                    <div class="postHeader_right"></div>
                </div>
            </div>
        <?php endforeach; ?>

    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('5 latest news') ?></h3>
            </div>
            <div class="panel-body">
                <?php foreach($this->top as $top): ?>
                    <a href="<?php echo $this->url('application/default', array('controller' => 'index', 'action' => 'show', 'id' => $top->getId())); ?>"><?php echo $top->getTitle(); ?></a> /
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</div>

<!-- <script type="text/javascript">
    var slideshow=new TINY.slider.slide('slideshow',{
        id:'slider',
        auto:4,
        resume:false,
        vertical:false,
        navid:'pagination',
        activeclass:'current',
        position:0,
        rewind:false,
        elastic:true,
        left:'slideleft',
        right:'slideright'
    });
</script> -->