<?php echo $this->headLink()->appendStylesheet('/css/login.css'); ?>
<?php //echo $this->headLink()->appendStylesheet('/js/tinyslider2/style.css'); ?>
<?php //echo $this->headScript()->prependFile('/js/tinyslider2/script.js'); ?>
<?php echo $this->headLink()->appendStylesheet('/js/picture-slider/style.css'); ?>
<?php echo $this->headScript()->prependFile('/js/picture-slider/script.js'); ?>
<?php echo $this->headScript()->prependFile('/js/likes.js'); ?>
<?php echo $this->headScript()->prependFile('/js/tinymce/tinymce.min.js'); ?>
<script>tinymce.init({ selector:'textarea' });</script>
<div class="row">
    <br/>
    <div class="col-md-8">

        <?php
        $flash = $this->flashMessenger();
        $flash->setMessageOpenFormat('<div%s>
                     <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                         &times;
                     </button>
                     <ul><li>')
            ->setMessageSeparatorString('</li><li>')
            ->setMessageCloseString('</li></ul></div>');

        echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
        echo $flash->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
        echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
        echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
        ?>

        <?php foreach($this->posts as $id => $post): ?>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div <?php $acl = $this->acl; if($this->identity()): if($this->acl->isAllowed($this->identity()->getUserRole(), $acl::NEWS)): ?> class="postHeader_left" <?php endif; endif; ?> >
                        <h4 class="panel-title"><?php echo $this->translate($post[key($post)]->getTitle()); ?></h4>
                    </div>
                    <?php if($this->identity()): if($this->acl->isAllowed($this->identity()->getUserRole(), $acl::NEWS)): ?>
                        <div class="postHeader_right">
                            <a href="<?php echo $this->url('posts/default', array('controller' => 'index', 'action' => 'post-edit', 'id' => $post[key($post)]->getId())); ?>"><span class="glyphicon glyphicon-edit"></span></a>
                            <a href="<?php echo $this->url('posts/default', array('controller' => 'index', 'action' => 'post-delete', 'id' => $post[key($post)]->getId())); ?>"><span class="glyphicon glyphicon-trash"></span></a>
                        </div>
                    <?php endif; endif; ?>
                </div>
                <div class="panel-body">

                    <?php if($this->identity()): ?>
                        <div class="slider">
                            <ul>
                                <li><img src="/img/tests/1.jpg" alt="" width="800px"></li>
                                <li><img src="/img/tests/2.jpg" alt="" width="800px"></li>
                            </ul>
                        </div>
                    <?php endif; ?>

                    <?php echo $post[key($post)]->getText(); ?>
                    <hr/>
                    <div class="postBottom_left">
                        <?php echo key($post).': '.$post[key($post)]->getCreated(); ?>
                    </div>
                    <div class="postHeader_right">
                        <?php if($this->identity()): ?>
                            <div class="addLike"><span class="glyphicon glyphicon-heart"></span>&nbsp;<?php echo $this->likes; ?></div>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>

        <?php if($this->identity()): ?>
            <div class="panel panel-default">
                <div class="panel-heading">
                    Leave comment:
                </div>
                <div class="panel-body">
                    <?php $this->commentForm->prepare(); ?>
                    <?= $this->form()->openTag($this->commentForm) ?>
                    <?= $this->formTextarea($this->commentForm->get('text')) ?><br/>
                    <?= $this->formSubmit($this->commentForm->get('submit')) ?>
                    <?= $this->form()->closeTag() ?>
                </div>
            </div>

            <?php if($this->comments): ?>
                <?php foreach($this->comments as $id => $comment): ?>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <?php echo $comment['userName']; ?>
                        </div>
                        <div class="panel-body">
                            <?php echo $comment['text'] ?>
                            <hr/>
                            <div class="postBottom_left">
                                <?php echo $comment['userName'].': '.$comment['created']; ?>
                            </div>
                            <div class="postHeader_right"></div>
                        </div>
                    </div>
                <?php endforeach; ?>
            <?php endif; ?>

        <?php endif; ?>

    </div>

    <div class="col-md-4">
        <?php echo $this->partial('_top-news.phtml', array(
            'top' => $this->top,
            'popularPosts' => $this->popularPosts,
        )); ?>
    </div>
</div>

<!-- <script type="text/javascript">
    var slideshow=new TINY.slider.slide('slideshow',{
        id:'slider',
        auto:4,
        resume:false,
        vertical:false,
        navid:'pagination',
        activeclass:'current',
        position:0,
        rewind:false,
        elastic:true,
        left:'slideleft',
        right:'slideright'
    });
</script> -->