<?php echo $this->headLink()->appendStylesheet('/css/login.css'); ?>
<div class="row">
    <br/>
    <div class="col-md-8">

        <?php
        $flash = $this->flashMessenger();
        $flash->setMessageOpenFormat('<div%s>
                     <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                         &times;
                     </button>
                     <ul><li>')
            ->setMessageSeparatorString('</li><li>')
            ->setMessageCloseString('</li></ul></div>');

        echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
        echo $flash->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
        echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
        echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
        ?>

        <?php foreach($this->posts as $id => $post): ?>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div <?php $acl = $this->acl; if($this->identity()): if($this->acl->isAllowed($this->identity()->getUserRole(), $acl::NEWS)): ?> class="postHeader_left" <?php endif; endif; ?> >
                        <h4 class="panel-title"><?php echo $this->translate($post[key($post)]->getTitle()); ?></h4>
                    </div>
                    <?php if($this->identity()): if($this->acl->isAllowed($this->identity()->getUserRole(), $acl::NEWS)): ?>
                        <div class="postHeader_right">
                            <a href="<?php echo $this->url('posts/default', array('controller' => 'index', 'action' => 'post-edit', 'id' => $post[key($post)]->getId())); ?>"><span class="glyphicon glyphicon-edit"></span></a>
                            <a href="<?php echo $this->url('posts/default', array('controller' => 'index', 'action' => 'post-delete', 'id' => $post[key($post)]->getId())); ?>"><span class="glyphicon glyphicon-trash"></span></a>
                        </div>
                    <?php endif; endif; ?>
                </div>
                <div class="panel-body">
                    <?php echo $post[key($post)]->getText(); ?>
                    <hr/>
                    <div class="postBottom_left">
                        <?php echo key($post).': '.$post[key($post)]->getCreated(); ?>
                    </div>
                    <div class="postHeader_right"></div>
                </div>
            </div>
        <?php endforeach; ?>

    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('5 latest news') ?></h3>
            </div>
            <div class="panel-body">
                <?php foreach($this->top as $top): ?>
                    <a href="<?php echo $this->url('application/default', array('controller' => 'index', 'action' => 'show', 'id' => $top->getId())); ?>"><?php echo $top->getTitle(); ?></a> /
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</div>
